title: Escape The X
email: your-email@domain.com
description: “Qualquer árvore que queira tocar os céus, precisa ter raízes tão profundas ao ponto de tocar os infernos”. 
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "escapethex.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Eduardo Barreto # add your name
author-pic: profile.jpg
about-author2: Prazer, <strong>Eduardo Barreto!</strong> Sou formado em <i>Gestão de TI</i>, Pós-graduado em <i>Data Science</i> e estou fazendo outra pós-graduação <i>Forense Computacional</i>. Gosto muito de assuntos relacionados com a <strong>TI</strong>, <strong>Produção Musical</strong> e <strong>Saúde Mental</strong>. Faço deste espaço aqui meu <strong>portfólio e também meu <strong>segundo blog</strong>, onde costumo publicar <strong>poemas, textos e projetos de minha autoria</strong>. Então filtre o que achar útil e saudável, aquilo que acrescenta, aquilo que leva o conhecimento!
about-author: 
# Contact links
#email: edu_barreto23@hotmail.com # Add your Email address
#website: # Add your website, do not add http://
linkedin: edubarreto23 # Add your Linkedin handle
#github: EscapeTheX # Add your Github handle
#facebook: edubarreto23 # Add your Facebook handle
instagram: escapethex # Add your Instagram handle

# Newsletter
#mailchimp: # Add your MailChimp form identifier.

# Disqus
#discus_identifier: # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
